/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/FTshx0olziu
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Manrope } from 'next/font/google'
import { Rethink_Sans } from 'next/font/google'

manrope({
  subsets: ['latin'],
  display: 'swap',
})

rethink_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function imported() {
  return (
    <div className="flex flex-col items-center justify-center min-h-[100dvh] bg-white">
      <div className="max-w-3xl px-6 py-12 text-center space-y-4">
        <h1 className="text-3xl font-bold md:text-4xl lg:text-5xl">Kashyap Challapalli</h1>
        <p className="text-gray-500 text-lg md:text-xl">
          pushing the barriers of human intelligence
        </p>
      </div>
    </div>
  );
}
